site_name: EDD
site_url: https://mydomain.org/mysite
theme:
  name: material
  logo: assets/logo.webp
  language: es
  palette:
    scheme: slate
    primary: white
  features:
  #- navigation.tabs
  - navigation.indexed
  - toc.integrate

plugins:
  - search
  - blog:
      archive_date_format: MMMM yyyy
      categories_allowed:
        - Holidays
        - News
nav:
  - Home: index.md
  - Blog:
     - blog/index.md
extra:
  generator: false
  social:
    - icon: fontawesome/brands/linkedin

copyright: Copyright &copy; 2016 - 2020 Martin Donath
repo_url: https://github.com/eddshared/eddshared.github.io
markdown_extensions: 
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji 
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
