authors:
  team:
    name: Team
    description: Creator
    avatar: https://simpleicons.org/icons/materialformkdocs.svg
  eddshared:
    name: Edd Shared
    description: Creator
    avatar: https://github.com/eddshared.png